/**
 * Generated by tsnapi — public API snapshot of `vitepress-theme-resume/markdown/experience`
 */
// #region Functions
export declare function experienceContainer(_: MarkdownIt): void;
// #endregion