/**
 * Generated by tsnapi — public API snapshot of `vitepress-theme-resume/config`
 */
// #region Other
export { baseConfig }
export { defaultResumeThemeOptions }
export { defineResumeConfig }
export { ResolvedResumeConfig }
export { resolveResumeConfig }
export { resolveResumeProfile }
export { ResumeFrontmatter }
export { ResumeProfile }
export { ResumeProfileTag }
export { ResumeThemeConfig }
export { ResumeThemeOptions }
// #endregion