/**
 * Generated by tsnapi — public API snapshot of `vitepress-theme-resume/config`
 */
// #region Functions
export declare function defineResumeConfig(_?: ResumeThemeConfig & UserConfig): UserConfig;
export declare function resolveResumeConfig(_: ResumeThemeOptions | undefined, _: ResumeFrontmatter): ResolvedResumeConfig;
export declare function resolveResumeProfile(_?: ResumeProfile, _?: Partial<ResumeProfile>): ResumeProfile | undefined;
// #endregion

// #region Variables
export declare const baseConfig: {
  themeConfig: {
    nav: never[];
    sidebar: never[];
  };
  vite: {
    ssr: {
      noExternal: string[];
    };
    optimizeDeps: {
      exclude: string[];
    };
  };
};
export declare const defaultResumeThemeOptions: Required<Pick<ResumeThemeOptions, "skipLinkLabel">> & ResumeThemeOptions;
// #endregion

// #region Other
export { ResolvedResumeConfig }
export { ResumeFrontmatter }
export { ResumeProfile }
export { ResumeProfileTag }
export { ResumeThemeConfig }
export { ResumeThemeOptions }
// #endregion