/**
 * Generated by tsnapi — public API snapshot of `vitepress-theme-resume`
 */
// #region Interfaces
export interface ResumeFrontmatter {
  resume?: boolean;
  profile?: ResumeProfile;
}
export interface ResumeProfile {
  name: string;
  meta?: string[];
  intent?: string[];
}
// #endregion

// #region Default Export
declare const _default: {
  Layout: import("vue").DefineComponent<{}, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
  enhanceApp({
    app
  }: import("vitepress").EnhanceAppContext): void;
};
export default _default
// #endregion