/**
 * Generated by tsnapi — public API snapshot of `vitepress-theme-resume`
 */
// #region Default Export
declare const _default: {
  Layout: import("vue").DefineComponent<{}, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
};
export default _default
// #endregion

// #region Other
export { experienceContainer }
export { ResumeFrontmatter }
export { ResumeProfile }
// #endregion