/**
 * Generated by tsnapi — public API snapshot of `vitepress-theme-resume`
 */
// #region Functions
export declare function useResumeConfig(): {
  config: import("vue").Ref<ResolvedResumeConfig, ResolvedResumeConfig>;
} | {
  config: import("vue").ComputedRef<ResolvedResumeConfig>;
};
export declare function useResumeMode(): import("vue").ComputedRef<boolean>;
export declare function useResumeProfile(): import("vue").ComputedRef<ResumeProfile | undefined>;
export declare function withResumeConfigProvider(_: Component): import("vue").DefineComponent<{}, () => import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
  [key: string]: any;
}>, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
// #endregion

// #region Variables
export declare const ResumeExperience: typeof __VLS_export$3;
export declare const ResumeHighlight: typeof __VLS_export$2;
export declare const ResumeHighlights: typeof __VLS_export$1;
export declare const ResumeSkillTag: typeof __VLS_export;
export declare const ResumeTheme: {
  Layout: import("vue").DefineComponent<{}, () => import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
    [key: string]: any;
  }>, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
  enhanceApp({
    app
  }: import("vitepress").EnhanceAppContext): void;
};
// #endregion

// #region Default Export
declare const _default: {
  Layout: import("vue").DefineComponent<{}, () => import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
    [key: string]: any;
  }>, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
  enhanceApp({
    app
  }: import("vitepress").EnhanceAppContext): void;
};
export default _default
// #endregion

// #region Other
export { baseConfig }
export { defaultResumeThemeOptions }
export { defineResumeConfig }
export { ResolvedResumeConfig }
export { ResumeFrontmatter }
export { ResumeProfile }
export { ResumeProfileTag }
export { ResumeThemeConfig }
export { ResumeThemeOptions }
// #endregion